BETS =   {      passline: { name: "Pass Line",
                            win_rolls: [7, 11],
                            loss_rolls: [2, 3, 12],
                            payouts: { 7 => 1, 11 => 1 },
                            needs_point: false},
                dontpass: { name: "Don't Pass",
                            win_rolls: [2, 3],
                            loss_rolls: [7, 11],
                            payouts: { 2 => 1, 3 => 1 },
                            needs_point: false},
                place4: {   name: "Place the Four",
                            win_rolls: [4],
                            loss_rolls: [7],
                            payouts: { 4 => (9/5.to_f) },
                            needs_point: false},
                place5: {   name: "Place the Five",
                            win_rolls: [5],
                            loss_rolls: [7],
                            payouts: { 5 => (7/5.to_f) },
                            needs_point: false},
                place6: {   name: "Place the Six",
                            win_rolls: [6],
                            loss_rolls: [7],
                            payouts: { 6 => (7/6.to_f) },
                            needs_point: false},
                place8: {   name: "Place the Eight",
                            win_rolls: [8],
                            loss_rolls: [7],
                            payouts: { 8 => (7/6.to_f) },
                            needs_point: false},
                place9: {   name: "Place the Nine",
                            win_rolls: [9],
                            loss_rolls: [7],
                            payouts: { 9 => (7/5.to_f) },
                            needs_point: false},
                place10: {  name: "Place the Ten",
                            win_rolls: [10],
                            loss_rolls: [7],
                            payouts: { 10 => (9/5.to_f) },
                            needs_point: false},
                field: {    name: "Field",
                            win_rolls: [2, 3, 4, 9, 10, 11, 12],
                            loss_rolls: [5, 6, 7, 8],
                            payouts: { 2 => 2, 3 => 1, 4 => 1, 9 => 1, 10 => 1, 11 => 1, 12 => 3 },
                            needs_point: false},
                hard4: {    name: "Hard Four",
                            win_rolls: [[2,2]],
                            loss_rolls: [[1,3],7],
                            payouts: { 4 => 7 },
                            needs_point: false},
                hard6: {    name: "Hard Six",
                            win_rolls: [[3,3]],
                            loss_rolls: [[2,4],[1,5],7],
                            payouts: { 6 => 9 },
                            needs_point: false},
                hard8: {    name: "Hard Eight",
                            win_rolls: [[4,4]],
                            loss_rolls: [[5,3],[6,2],7],
                            payouts: { 8 => 9 },
                            needs_point: false},
                hard10: {   name: "Hard Ten",
                            win_rolls: [[5,5]],
                            loss_rolls: [[6,4],7],
                            payouts: { 10 => 7 },
                            needs_point: false},
                aces: {     name: "Aces",
                            win_rolls: [2],
                            loss_rolls: (3..12).to_a,
                            payouts: { 2 => 30 },
                            needs_point: false},
                craps: {    name: "Craps",
                            win_rolls: [2, 3, 12],
                            loss_rolls: (4..11).to_a,
                            payouts: { 2 => 7, 3 => 7 , 12 => 7},
                            needs_point: false},
                yo: {       name: "Eleven",
                            win_rolls: [11],
                            loss_rolls: ((2..10).to_a + [12]),
                            payouts: { 11 => 15 },
                            needs_point: false},
                ace_deuce: {name: "Ace Deuce",
                            win_rolls: [3],
                            loss_rolls: ([2] + (4..12).to_a),
                            payouts: { 3 => 15 },
                            needs_point: false},
                midnight: { name: "Midnight",
                            win_rolls: [12],
                            loss_rolls: (2..11).to_a,
                            payouts: { 12 => 30 },
                            needs_point: false},
                any_seven: {name: "Any Seven",
                            win_rolls: [7],
                            loss_rolls: ((2..6).to_a + (8..12).to_a),
                            payouts: { 7 => 4 },
                            needs_point: false},
                world: {    name: "World",
                            win_rolls: [2, 3, 7, 11, 12],
                            loss_rolls: [4, 5, 6, 8, 9, 10],
                            payouts: { 2 => (30/5.to_f),
                                       3 => (15/5.to_f),
                                       7 => (4/5.to_f),
                                       11 => (15/5.to_f),
                                       12 => (30/5.to_f) },
                                       needs_point: false},
                odds:     { name: "Odds",
                            win_rolls: [],
                            loss_rolls: [7],
                            payouts: { 7 => 0 },
                            needs_point: true},
                come:     { name: "Come",
                            win_rolls: [7, 11],
                            loss_rolls: [2, 3, 12],
                            payouts: { 7 => 1, 11 => 1 },
                            needs_point: true},
                dontcome: { name: "Dont Come",
                            win_rolls: [2, 3],
                            loss_rolls: [7, 11],
                            payouts: { 2 => 1, 3 => 1 },
                            needs_point: true}
           }